### ISSUE TITLE
Need to add "timeout" param into the get or post function 

### ISSUE THREAD

**Issue by BruceDone** [djm/python-scrapyd-api#11]
Hi djm:
    Since scrapyd server may be down , so while you using this scrapyd api , you may be block by the http error or other error, need to add the timeout param to handle this situation.

**Comment by tlinhart** [comment]
I would appreciate this as well. I might prepare PR which would basically:
- add new `ScrapydAPI` constructor parameter called `timeout` (same type as `requests.request` expects) storing it in instance attribute `timeout`
- use this attribute in every client's GET/POST request inside `wrapper.py`

What do you think?

**Comment by djm** [comment]
@tlinhart It's been a while but yes, that sounds good. I would accept a PR with that interface.

**Comment by tlinhart** [comment]
Thanks @djm for merging!

**Comment by djm** [comment]
No worries, thanks for proposing and enacting it!

I'll do the PyPI release this evening and update this thread.

**Comment by djm** [comment]
That's out now, [v2.1.0](https://pypi.python.org/pypi/python-scrapyd-api/2.1.0).

Thanks again :)

**Comment by tlinhart** [comment]
Thank you too, @djm . Just wanted to ask how documentation gets updated. Changes are not reflected there.

**Comment by djm** [comment]
@tlinhart Thanks for the reminder. I've [fixed that](http://python-scrapyd-api.readthedocs.io/en/latest/usage.html#setting-timeout-for-the-requests) + converted the base docs to Markdown as PyPI Warehouse finally supports it 🎉.
