### ISSUE TITLE
Add support for new Daemon Status Endpoint

### ISSUE THREAD

**Issue by djm** [djm/python-scrapyd-api#5]
See the docs here: http://scrapyd.readthedocs.org/en/latest/api.html#daemonstatus-json

Happy for someone to take this on.

**Comment by Digenis** [comment]
This is not in a stable branch yet.
Whoever set up the readthedocs integration
forgot to set it up the same way as in scrapy (and its release policy).

**Comment by djm** [comment]
@Digenis Thanks for the heads up.

Will close this for now, can re-open it later when the times comes.
