### ISSUE TITLE
request passing a spider argument

### ISSUE THREAD

**Issue by podolskyi** [djm/python-scrapyd-api#8]
Hi, thanks for the very helpful API wrapper.
I can't find API for send custom argument to the spider, this feature supports in this version? 
scrapyd docs: https://scrapyd.readthedocs.io/en/latest/api.html#schedule-json

**Comment by BruceDone** [comment]
yes , this feature has  already been supported .this is how i call by the api 
`job = scrapyd.schedule(project=project, spider=spider, storage_key=storage_key)`  
as you can see ,the storage_key is an custom argument, and the spider you code you should edit like this: 

```
class ImageSpider(Spider):
    name = 'image'

    start_urls = []

    def __init__(self, get_image_url_api, *args, **kwargs):
        self.storage_key = kwargs.get('storage_key', None)
        queue_count = kwargs.get('count', None)
        if queue_count:
            get_image_url_api = re.sub('count=[0-9]+', 'count=' + str(queue_count), get_image_url_api)
        self.start_urls = [get_image_url_api % self.storage_key]
```

and it runs ok on my server.

**Comment by podolskyi** [comment]
Yeah, thanks.

**Comment by djm** [comment]
Thanks for answering @BruceDone.
